package core

func ProtocolManifest() ProtocolManifestResponse {
	return ProtocolManifestResponse{
		ProtocolVersion: "mergeos.protocol.manifest.v1",
		Kind:            "protocol_manifest",
		Schemas: []ProtocolManifestSchema{
			{
				Version:     "mergeos.task.v1",
				Kind:        "task",
				SchemaURL:   "https://mergeos.shop/protocol/task.v1.schema.json",
				Description: "Claimable bounty task with reward, worker lane, acceptance criteria, and evidence requirements.",
			},
			{
				Version:     "mergeos.task-claim.v1",
				Kind:        "task_claim",
				SchemaURL:   "https://mergeos.shop/protocol/task-claim.v1.schema.json",
				Description: "Authenticated bounty claim document with worker identity, payout proof hash, accepted task, and ledger-backed status.",
			},
			{
				Version:     "mergeos.agent.v1",
				Kind:        "agent",
				SchemaURL:   "https://mergeos.shop/protocol/agent.v1.schema.json",
				Description: "AI agent lane with supported actions, capabilities, active bounty demand, and open task references.",
			},
			{
				Version:     "mergeos.agent-action.v1",
				Kind:        "agent_action",
				SchemaURL:   "https://mergeos.shop/protocol/agent-action.v1.schema.json",
				Description: "Authenticated AI agent action document for review, test, generate, scan, and deployment evidence.",
			},
			{
				Version:     "mergeos.marketplace.v1",
				Kind:        "marketplace",
				SchemaURL:   "https://mergeos.shop/protocol/marketplace.v1.schema.json",
				Description: "Public realtime marketplace with funded projects, open bounties, active contributors, AI agent demand, and funding stats.",
			},
			{
				Version:     "mergeos.live-feed.v1",
				Kind:        "live_feed",
				SchemaURL:   "https://mergeos.shop/protocol/live-feed.v1.schema.json",
				Description: "Public realtime command center feed with project, task, PR, deployment, ledger, contributor, and AI action updates.",
			},
			{
				Version:     "mergeos.workflow.v1",
				Kind:        "workflow",
				SchemaURL:   "https://mergeos.shop/protocol/workflow.v1.schema.json",
				Description: "Project workflow graph with progress, current AI workflow step, task nodes, dependency edges, readiness, and release status.",
			},
			{
				Version:     "mergeos.estimate.v1",
				Kind:        "project_estimate",
				SchemaURL:   "https://mergeos.shop/protocol/estimate.v1.schema.json",
				Description: "Authenticated project estimate document with editable budget range, confidence, assumptions, risks, and cost breakdown.",
			},
			{
				Version:     "mergeos.wallet-migration.v1",
				Kind:        "wallet_migration",
				SchemaURL:   "https://mergeos.shop/protocol/wallet-migration.v1.schema.json",
				Description: "Authenticated legacy TRC20/EVM wallet migration document with Solana target wallet, legacy address hash, and Anchor register_legacy_wallet arguments.",
			},
			{
				Version:     "mergeos.repo-import.v1",
				Kind:        "repo_import",
				SchemaURL:   "https://mergeos.shop/protocol/repo-import.v1.schema.json",
				Description: "Public repository issue import document with scored GitHub issues, effort estimates, worker lane routing, and AI task generation inputs.",
			},
			{
				Version:     "mergeos.repo-sync.v1",
				Kind:        "repo_sync",
				SchemaURL:   "https://mergeos.shop/protocol/repo-sync.v1.schema.json",
				Description: "Authenticated project repository sync report with imported, added, updated, open, and closed issue counts for task generation.",
			},
			{
				Version:     "mergeos.dispute.v1",
				Kind:        "dispute",
				SchemaURL:   "https://mergeos.shop/protocol/dispute.v1.schema.json",
				Description: "Authenticated delivery dispute document for customer, worker, or admin escalation into the moderation queue.",
			},
			{
				Version:     "mergeos.ai-workflow.v1",
				Kind:        "ai_workflow",
				SchemaURL:   "https://mergeos.shop/protocol/ai-workflow.v1.schema.json",
				Description: "Authenticated AI orchestration workflow with repository import, issue scan, task generation, reward estimation, contributor routing, PR review, and deployment validation stages.",
			},
			{
				Version:     "mergeos.event.v1",
				Kind:        "event",
				SchemaURL:   "https://mergeos.shop/protocol/event.v1.schema.json",
				Description: "Realtime project, task, PR, deployment, ledger, and AI agent event envelope.",
			},
			{
				Version:     "mergeos.ledger.v1",
				Kind:        "ledger",
				SchemaURL:   "https://mergeos.shop/protocol/ledger.v1.schema.json",
				Description: "Public ledger entries with hash-chain verification metadata for payouts, fees, token minting, and manual credits.",
			},
			{
				Version:     "mergeos.escrow.v1",
				Kind:        "escrow",
				SchemaURL:   "https://mergeos.shop/protocol/escrow.v1.schema.json",
				Description: "Authenticated project escrow document with reserve, release, payout, remaining balance, and per-task settlement state.",
			},
			{
				Version:     "mergeos.payouts.v1",
				Kind:        "payouts",
				SchemaURL:   "https://mergeos.shop/protocol/payouts.v1.schema.json",
				Description: "Authenticated payout settlement document with release status, paid/open task counts, ledger proof references, payout accounts, and per-task payment state.",
			},
			{
				Version:     "mergeos.deployment.v1",
				Kind:        "deployment",
				SchemaURL:   "https://mergeos.shop/protocol/deployment.v1.schema.json",
				Description: "Authenticated deployment validation document with release gate progress, rollout stages, deployment evidence, and AI/deployment signals.",
			},
			{
				Version:     "mergeos.pr-monitor.v1",
				Kind:        "pr_monitor",
				SchemaURL:   "https://mergeos.shop/protocol/pr-monitor.v1.schema.json",
				Description: "Authenticated live pull request monitor with task linkage, readiness gates, merge risk, labels, authors, and GitHub sync health.",
			},
			{
				Version:     "mergeos.scan.v1",
				Kind:        "repository_scan",
				SchemaURL:   "https://mergeos.shop/protocol/scan.v1.schema.json",
				Description: "Repository scan findings for security, dependency, quality, and technical debt signals.",
			},
			{
				Version:     "mergeos.customer-dashboard.v1",
				Kind:        "customer_dashboard",
				SchemaURL:   "https://mergeos.shop/protocol/customer-dashboard.v1.schema.json",
				Description: "Authenticated customer delivery dashboard with project overview, escrow, payouts, deployment, AI workflow, task graph, repository scan, and PR monitor data.",
			},
			{
				Version:     "mergeos.worker-dashboard.v1",
				Kind:        "worker_dashboard",
				SchemaURL:   "https://mergeos.shop/protocol/worker-dashboard.v1.schema.json",
				Description: "Authenticated worker dashboard with claimed tasks, rewards, reputation audit, matched proposals, and linked identity status.",
			},
			{
				Version:     "mergeos.admin-ops.v1",
				Kind:        "admin_ops",
				SchemaURL:   "https://mergeos.shop/protocol/admin-ops.v1.schema.json",
				Description: "Authenticated admin operations queue for treasury review, disputes, moderation, payout audits, security checks, and fraud signals.",
			},
		},
		Endpoints: []ProtocolManifestEndpoint{
			{
				Method:      "GET",
				Path:        "/api/public/protocol",
				Auth:        "none",
				Description: "Protocol manifest and endpoint discovery for external agents and integrations.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/tasks",
				Protocol:    "mergeos.task.v1",
				Auth:        "none",
				Description: "Public open bounty tasks as protocol documents.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/marketplace",
				Protocol:    "mergeos.marketplace.v1",
				Auth:        "none",
				Description: "Public realtime marketplace for funded projects, open bounties, contributors, and AI agent lanes.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/live-feed",
				Protocol:    "mergeos.live-feed.v1",
				Auth:        "none",
				Description: "Public command center feed for project, task, PR, deployment, ledger, contributor, and AI action updates.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/agents",
				Protocol:    "mergeos.agent.v1",
				Auth:        "none",
				Description: "Public AI agent lanes as protocol documents.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/ledger",
				Protocol:    "mergeos.ledger.v1",
				Auth:        "none",
				Description: "Public ledger proof document with sanitized ledger rows and hash-chain verification.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/events",
				Protocol:    "mergeos.event.v1",
				Auth:        "none",
				Description: "Public live-feed events as protocol documents.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/projects/{id}/deployment",
				Protocol:    "mergeos.deployment.v1",
				Auth:        "none",
				Description: "Public sanitized deployment readiness document for marketplace projects, release gates, agent signals, and deployment validation progress.",
			},
			{
				Method:      "POST",
				Path:        "/api/public/repo/issues",
				Protocol:    "mergeos.repo-import.v1",
				Auth:        "none",
				Description: "Public GitHub repository issue import and AI scoring report.",
			},
			{
				Method:      "WS",
				Path:        "/api/ws",
				Protocol:    "mergeos.event.v1",
				Auth:        "none",
				Description: "Realtime WebSocket stream for live feed snapshots and protocol event broadcasts.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/protocol/workflow",
				Protocol:    "mergeos.workflow.v1",
				Auth:        "project",
				Description: "Authenticated project workflow graph protocol document.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/protocol/scan",
				Protocol:    "mergeos.scan.v1",
				Auth:        "project",
				Description: "Authenticated repository scan protocol document.",
			},
			{
				Method:      "POST",
				Path:        "/api/projects/{id}/repo-sync",
				Protocol:    "mergeos.repo-sync.v1",
				Auth:        "project",
				Description: "Authenticated issue sync report that converts imported GitHub issues into MergeOS task rows.",
			},
			{
				Method:      "POST",
				Path:        "/api/disputes",
				Protocol:    "mergeos.dispute.v1",
				Auth:        "user",
				Description: "Authenticated customer, worker, or admin dispute escalation into the admin moderation queue.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/escrow",
				Protocol:    "mergeos.escrow.v1",
				Auth:        "project",
				Description: "Authenticated project escrow reserve, release, payout, and task settlement document.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/payouts",
				Protocol:    "mergeos.payouts.v1",
				Auth:        "project",
				Description: "Authenticated project payout settlement document with release state, payout rows, ledger proof references, and payout accounts.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/deployment",
				Protocol:    "mergeos.deployment.v1",
				Auth:        "project",
				Description: "Authenticated deployment validation state with rollout stages, release gates, and evidence signals.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/ai-workflow",
				Protocol:    "mergeos.ai-workflow.v1",
				Auth:        "project",
				Description: "Authenticated AI orchestration timeline for repository import, issue scan, task generation, routing, PR review, and deployment validation.",
			},
			{
				Method:      "POST",
				Path:        "/api/projects/{id}/agent-actions",
				Protocol:    "mergeos.agent-action.v1",
				Auth:        "project",
				Description: "Authenticated AI agent evidence writer for review, test, generate, scan, and deployment actions.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/pull-requests",
				Protocol:    "mergeos.pr-monitor.v1",
				Auth:        "project",
				Description: "Authenticated live pull request monitor for linked bounty tasks, readiness gates, and merge risk.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/dashboard",
				Protocol:    "mergeos.customer-dashboard.v1",
				Auth:        "project",
				Description: "Authenticated customer dashboard for delivery status, escrow, workflow graph, repository scan, AI activity, and live PR monitoring.",
			},
			{
				Method:      "GET",
				Path:        "/api/workers/me",
				Protocol:    "mergeos.worker-dashboard.v1",
				Auth:        "worker",
				Description: "Authenticated worker dashboard for claimed work, payout references, reputation, and proposal routing.",
			},
			{
				Method:      "POST",
				Path:        "/api/projects/evaluate-price",
				Protocol:    "mergeos.estimate.v1",
				Auth:        "user",
				Description: "Authenticated project estimate for editable budget range, confidence, cost breakdown, assumptions, and risks.",
			},
			{
				Method:      "POST",
				Path:        "/api/wallets/migrations",
				Protocol:    "mergeos.wallet-migration.v1",
				Auth:        "user",
				Description: "Authenticated legacy TRC20/EVM wallet migration into a Solana MRG wallet with Anchor contract registration metadata.",
			},
			{
				Method:      "POST",
				Path:        "/api/tasks/{id}/accept",
				Protocol:    "mergeos.task-claim.v1",
				Auth:        "worker",
				Description: "Authenticated task claim endpoint for public bounty claim ids or internal task ids.",
			},
			{
				Method:      "GET",
				Path:        "/api/admin/ops-queue",
				Protocol:    "mergeos.admin-ops.v1",
				Auth:        "admin",
				Description: "Authenticated admin operations queue for disputes, moderation, payout review, treasury audit, security checks, and fraud signals.",
			},
		},
	}
}
