package core

func ProtocolManifest() ProtocolManifestResponse {
	return ProtocolManifestResponse{
		ProtocolVersion: "mergeos.protocol.manifest.v1",
		Kind:            "protocol_manifest",
		Schemas: []ProtocolManifestSchema{
			{
				Version:     "mergeos.task.v1",
				Kind:        "task",
				SchemaURL:   "https://mergeos.shop/protocol/task.v1.schema.json",
				Description: "Claimable bounty task with reward, worker lane, acceptance criteria, and evidence requirements.",
			},
			{
				Version:     "mergeos.agent.v1",
				Kind:        "agent",
				SchemaURL:   "https://mergeos.shop/protocol/agent.v1.schema.json",
				Description: "AI agent lane with supported actions, capabilities, active bounty demand, and open task references.",
			},
			{
				Version:     "mergeos.marketplace.v1",
				Kind:        "marketplace",
				SchemaURL:   "https://mergeos.shop/protocol/marketplace.v1.schema.json",
				Description: "Public realtime marketplace with funded projects, open bounties, active contributors, AI agent demand, and funding stats.",
			},
			{
				Version:     "mergeos.live-feed.v1",
				Kind:        "live_feed",
				SchemaURL:   "https://mergeos.shop/protocol/live-feed.v1.schema.json",
				Description: "Public realtime command center feed with project, task, PR, deployment, ledger, contributor, and AI action updates.",
			},
			{
				Version:     "mergeos.workflow.v1",
				Kind:        "workflow",
				SchemaURL:   "https://mergeos.shop/protocol/workflow.v1.schema.json",
				Description: "Project workflow graph with progress, current AI workflow step, task nodes, dependency edges, readiness, and release status.",
			},
			{
				Version:     "mergeos.event.v1",
				Kind:        "event",
				SchemaURL:   "https://mergeos.shop/protocol/event.v1.schema.json",
				Description: "Realtime project, task, PR, deployment, ledger, and AI agent event envelope.",
			},
			{
				Version:     "mergeos.ledger.v1",
				Kind:        "ledger",
				SchemaURL:   "https://mergeos.shop/protocol/ledger.v1.schema.json",
				Description: "Public ledger entries with hash-chain verification metadata for payouts, fees, token minting, and manual credits.",
			},
			{
				Version:     "mergeos.escrow.v1",
				Kind:        "escrow",
				SchemaURL:   "https://mergeos.shop/protocol/escrow.v1.schema.json",
				Description: "Authenticated project escrow document with reserve, release, payout, remaining balance, and per-task settlement state.",
			},
			{
				Version:     "mergeos.deployment.v1",
				Kind:        "deployment",
				SchemaURL:   "https://mergeos.shop/protocol/deployment.v1.schema.json",
				Description: "Authenticated deployment validation document with release gate progress, rollout stages, deployment evidence, and AI/deployment signals.",
			},
			{
				Version:     "mergeos.pr-monitor.v1",
				Kind:        "pr_monitor",
				SchemaURL:   "https://mergeos.shop/protocol/pr-monitor.v1.schema.json",
				Description: "Authenticated live pull request monitor with task linkage, readiness gates, merge risk, labels, authors, and GitHub sync health.",
			},
			{
				Version:     "mergeos.scan.v1",
				Kind:        "repository_scan",
				SchemaURL:   "https://mergeos.shop/protocol/scan.v1.schema.json",
				Description: "Repository scan findings for security, dependency, quality, and technical debt signals.",
			},
			{
				Version:     "mergeos.customer-dashboard.v1",
				Kind:        "customer_dashboard",
				SchemaURL:   "https://mergeos.shop/protocol/customer-dashboard.v1.schema.json",
				Description: "Authenticated customer delivery dashboard with project overview, escrow, deployment, AI workflow, task graph, repository scan, and PR monitor data.",
			},
			{
				Version:     "mergeos.worker-dashboard.v1",
				Kind:        "worker_dashboard",
				SchemaURL:   "https://mergeos.shop/protocol/worker-dashboard.v1.schema.json",
				Description: "Authenticated worker dashboard with claimed tasks, rewards, reputation audit, matched proposals, and linked identity status.",
			},
			{
				Version:     "mergeos.admin-ops.v1",
				Kind:        "admin_ops",
				SchemaURL:   "https://mergeos.shop/protocol/admin-ops.v1.schema.json",
				Description: "Authenticated admin operations queue for treasury review, disputes, moderation, payout audits, security checks, and fraud signals.",
			},
		},
		Endpoints: []ProtocolManifestEndpoint{
			{
				Method:      "GET",
				Path:        "/api/public/protocol",
				Auth:        "none",
				Description: "Protocol manifest and endpoint discovery for external agents and integrations.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/tasks",
				Protocol:    "mergeos.task.v1",
				Auth:        "none",
				Description: "Public open bounty tasks as protocol documents.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/marketplace",
				Protocol:    "mergeos.marketplace.v1",
				Auth:        "none",
				Description: "Public realtime marketplace for funded projects, open bounties, contributors, and AI agent lanes.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/live-feed",
				Protocol:    "mergeos.live-feed.v1",
				Auth:        "none",
				Description: "Public command center feed for project, task, PR, deployment, ledger, contributor, and AI action updates.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/agents",
				Protocol:    "mergeos.agent.v1",
				Auth:        "none",
				Description: "Public AI agent lanes as protocol documents.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/ledger",
				Protocol:    "mergeos.ledger.v1",
				Auth:        "none",
				Description: "Public ledger proof document with sanitized ledger rows and hash-chain verification.",
			},
			{
				Method:      "GET",
				Path:        "/api/public/protocol/events",
				Protocol:    "mergeos.event.v1",
				Auth:        "none",
				Description: "Public live-feed events as protocol documents.",
			},
			{
				Method:      "WS",
				Path:        "/api/ws",
				Protocol:    "mergeos.event.v1",
				Auth:        "none",
				Description: "Realtime WebSocket stream for live feed snapshots and protocol event broadcasts.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/protocol/workflow",
				Protocol:    "mergeos.workflow.v1",
				Auth:        "project",
				Description: "Authenticated project workflow graph protocol document.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/protocol/scan",
				Protocol:    "mergeos.scan.v1",
				Auth:        "project",
				Description: "Authenticated repository scan protocol document.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/escrow",
				Protocol:    "mergeos.escrow.v1",
				Auth:        "project",
				Description: "Authenticated project escrow reserve, release, payout, and task settlement document.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/deployment",
				Protocol:    "mergeos.deployment.v1",
				Auth:        "project",
				Description: "Authenticated deployment validation state with rollout stages, release gates, and evidence signals.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/pull-requests",
				Protocol:    "mergeos.pr-monitor.v1",
				Auth:        "project",
				Description: "Authenticated live pull request monitor for linked bounty tasks, readiness gates, and merge risk.",
			},
			{
				Method:      "GET",
				Path:        "/api/projects/{id}/dashboard",
				Protocol:    "mergeos.customer-dashboard.v1",
				Auth:        "project",
				Description: "Authenticated customer dashboard for delivery status, escrow, workflow graph, repository scan, AI activity, and live PR monitoring.",
			},
			{
				Method:      "GET",
				Path:        "/api/workers/me",
				Protocol:    "mergeos.worker-dashboard.v1",
				Auth:        "worker",
				Description: "Authenticated worker dashboard for claimed work, payout references, reputation, and proposal routing.",
			},
			{
				Method:      "GET",
				Path:        "/api/admin/ops-queue",
				Protocol:    "mergeos.admin-ops.v1",
				Auth:        "admin",
				Description: "Authenticated admin operations queue for disputes, moderation, payout review, treasury audit, security checks, and fraud signals.",
			},
		},
	}
}
